name: 'Build & Test'

on:
  push:
    branches:
      - main
      - dev

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Install V
        uses: vlang/setup-v@v1.3
        with:
          check-latest: true

      - name: Checkout
        uses: actions/checkout@v3

      - name: Run tests
        run: make test

      - name: Build artifacts
        run: make build
