name: 'Build & Test'

on:
  push:
    branches:
      - main
      - dev

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Create network
        run: docker network create gateway

      - name: Run tests
        run: make test

      - name: Build artifacts
        run: make build
